kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "service2-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: '#!groovy def datas node("skopeo") {}'
    type: JenkinsPipeline


